services:
    app.next_prime_number.factory:
        class: AppBundle\Factory\NextPrimeNumberFactory
        arguments:
            - "@app.prime_number_validation.service"

    app.next_prime_number.service:
        class: AppBundle\Service\AbstractNextPrimeNumberService
        factory: 'app.next_prime_number.factory:createNextPrimeNumberService'

    app.prime_number_validation.service:
        class: AppBundle\Service\PrimeNumberValidationService

    app.prime_numbers_service.factory:
        class: AppBundle\Factory\PrimeNumbersServiceFactory
        arguments:
            - "@app.last_prime_numbers.service"
            - "@app.quantity_prime_numbers.service"

    app.last_prime_numbers.service:
        class: AppBundle\Service\LastPrimeNumbersService
        arguments:
            - "@app.next_prime_number.service"
            - "@app.prime_number_validation.service"

    app.quantity_prime_numbers.service:
        class: AppBundle\Service\QuantityPrimeNumbersService
        arguments:
            - "@app.next_prime_number.service"
            - "@app.prime_number_validation.service"

    app.prime_numbers_table.presenter:
        class: AppBundle\Presenter\NumbersTablePresenter
        arguments:
            - '@app.prime_numbers_calculator'

    app.prime_numbers_list.presenter:
        class: AppBundle\Presenter\NumbersListPresenter
        arguments:
            - '@app.prime_numbers_calculator'

    app.prime_numbers_calculator:
        class: AppBundle\Calculator\Multiplication
